//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 05:31:26 PM EDT 
//


package gov.ca.emsa.transactions.patientDiscovery;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Abenakian.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Abenakian">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="x-AAQ"/>
 *     &lt;enumeration value="x-MAC"/>
 *     &lt;enumeration value="x-ABE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Abenakian")
@XmlEnum
public enum Abenakian {

    @XmlEnumValue("x-AAQ")
    X_AAQ("x-AAQ"),
    @XmlEnumValue("x-MAC")
    X_MAC("x-MAC"),
    @XmlEnumValue("x-ABE")
    X_ABE("x-ABE");
    private final String value;

    Abenakian(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Abenakian fromValue(String v) {
        for (Abenakian c: Abenakian.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
