//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 05:31:26 PM EDT 
//


package gov.ca.emsa.transactions.patientDiscovery;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.ca.emsa.transactions.patientDiscovery package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IVLREALWidth_QNAME = new QName("urn:hl7-org:v3", "width");
    private final static QName _IVLREALCenter_QNAME = new QName("urn:hl7-org:v3", "center");
    private final static QName _IVLREALLow_QNAME = new QName("urn:hl7-org:v3", "low");
    private final static QName _IVLREALHigh_QNAME = new QName("urn:hl7-org:v3", "high");
    private final static QName _COCTMT150000UV02OrganizationContainsPartOrganization_QNAME = new QName("urn:hl7-org:v3", "partOrganization");
    private final static QName _COCTMT090300UV01DeviceAsLocatedEntity_QNAME = new QName("urn:hl7-org:v3", "asLocatedEntity");
    private final static QName _COCTMT150000UV02ContactPartyContactPerson_QNAME = new QName("urn:hl7-org:v3", "contactPerson");
    private final static QName _COCTMT710000UV01LocatedEntityHasPartsLocatedPlace_QNAME = new QName("urn:hl7-org:v3", "locatedPlace");
    private final static QName _COCTMT090300UV01LicensedEntityIssuingOrganization_QNAME = new QName("urn:hl7-org:v3", "issuingOrganization");
    private final static QName _COCTMT090100UV01AssignedPersonRepresentedOrganization_QNAME = new QName("urn:hl7-org:v3", "representedOrganization");
    private final static QName _COCTMT090100UV01AssignedPersonAssignedPerson_QNAME = new QName("urn:hl7-org:v3", "assignedPerson");
    private final static QName _PRPAMT201306UV02MatchCriterionListMatchAlgorithm_QNAME = new QName("urn:hl7-org:v3", "matchAlgorithm");
    private final static QName _PRPAMT201306UV02MatchCriterionListMatchWeight_QNAME = new QName("urn:hl7-org:v3", "matchWeight");
    private final static QName _PRPAMT201306UV02MatchCriterionListMinimumDegreeMatch_QNAME = new QName("urn:hl7-org:v3", "minimumDegreeMatch");
    private final static QName _COCTMT090300UV01AssignedDeviceAssignedDevice_QNAME = new QName("urn:hl7-org:v3", "assignedDevice");
    private final static QName _MCCIMT000100UV01OrganizationNotificationParty_QNAME = new QName("urn:hl7-org:v3", "notificationParty");
    private final static QName _COCTMT710000UV01LocatedEntityPartOfLocation_QNAME = new QName("urn:hl7-org:v3", "location");
    private final static QName _PRPAIN201305UV02QUQIMT021001UV01ControlActProcessQueryByParameter_QNAME = new QName("urn:hl7-org:v3", "queryByParameter");
    private final static QName _COCTMT040203UV01NotificationPartyContactOrganization_QNAME = new QName("urn:hl7-org:v3", "contactOrganization");
    private final static QName _ENFamily_QNAME = new QName("urn:hl7-org:v3", "family");
    private final static QName _ENSuffix_QNAME = new QName("urn:hl7-org:v3", "suffix");
    private final static QName _ENValidTime_QNAME = new QName("urn:hl7-org:v3", "validTime");
    private final static QName _ENDelimiter_QNAME = new QName("urn:hl7-org:v3", "delimiter");
    private final static QName _ENPrefix_QNAME = new QName("urn:hl7-org:v3", "prefix");
    private final static QName _ENGiven_QNAME = new QName("urn:hl7-org:v3", "given");
    private final static QName _COCTMT150000UV02OrganizationPartOfWholeOrganization_QNAME = new QName("urn:hl7-org:v3", "wholeOrganization");
    private final static QName _PRPAMT201306UV02QueryByParameterMatchCriterionList_QNAME = new QName("urn:hl7-org:v3", "matchCriterionList");
    private final static QName _COCTMT090100UV01RoleOtherScopingOrganization_QNAME = new QName("urn:hl7-org:v3", "scopingOrganization");
    private final static QName _MCCIMT000100UV01DeviceAsAgent_QNAME = new QName("urn:hl7-org:v3", "asAgent");
    private final static QName _ADDirection_QNAME = new QName("urn:hl7-org:v3", "direction");
    private final static QName _ADStreetAddressLine_QNAME = new QName("urn:hl7-org:v3", "streetAddressLine");
    private final static QName _ADState_QNAME = new QName("urn:hl7-org:v3", "state");
    private final static QName _ADDeliveryMode_QNAME = new QName("urn:hl7-org:v3", "deliveryMode");
    private final static QName _ADStreetName_QNAME = new QName("urn:hl7-org:v3", "streetName");
    private final static QName _ADUnitType_QNAME = new QName("urn:hl7-org:v3", "unitType");
    private final static QName _ADUseablePeriod_QNAME = new QName("urn:hl7-org:v3", "useablePeriod");
    private final static QName _ADCensusTract_QNAME = new QName("urn:hl7-org:v3", "censusTract");
    private final static QName _ADCounty_QNAME = new QName("urn:hl7-org:v3", "county");
    private final static QName _ADHouseNumber_QNAME = new QName("urn:hl7-org:v3", "houseNumber");
    private final static QName _ADPostalCode_QNAME = new QName("urn:hl7-org:v3", "postalCode");
    private final static QName _ADHouseNumberNumeric_QNAME = new QName("urn:hl7-org:v3", "houseNumberNumeric");
    private final static QName _ADStreetNameBase_QNAME = new QName("urn:hl7-org:v3", "streetNameBase");
    private final static QName _ADCity_QNAME = new QName("urn:hl7-org:v3", "city");
    private final static QName _ADBuildingNumberSuffix_QNAME = new QName("urn:hl7-org:v3", "buildingNumberSuffix");
    private final static QName _ADCountry_QNAME = new QName("urn:hl7-org:v3", "country");
    private final static QName _ADDeliveryInstallationQualifier_QNAME = new QName("urn:hl7-org:v3", "deliveryInstallationQualifier");
    private final static QName _ADDeliveryInstallationType_QNAME = new QName("urn:hl7-org:v3", "deliveryInstallationType");
    private final static QName _ADUnitID_QNAME = new QName("urn:hl7-org:v3", "unitID");
    private final static QName _ADCareOf_QNAME = new QName("urn:hl7-org:v3", "careOf");
    private final static QName _ADDeliveryInstallationArea_QNAME = new QName("urn:hl7-org:v3", "deliveryInstallationArea");
    private final static QName _ADPrecinct_QNAME = new QName("urn:hl7-org:v3", "precinct");
    private final static QName _ADDeliveryAddressLine_QNAME = new QName("urn:hl7-org:v3", "deliveryAddressLine");
    private final static QName _ADStreetNameType_QNAME = new QName("urn:hl7-org:v3", "streetNameType");
    private final static QName _ADDeliveryModeIdentifier_QNAME = new QName("urn:hl7-org:v3", "deliveryModeIdentifier");
    private final static QName _ADAdditionalLocator_QNAME = new QName("urn:hl7-org:v3", "additionalLocator");
    private final static QName _ADPostBox_QNAME = new QName("urn:hl7-org:v3", "postBox");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.ca.emsa.transactions.patientDiscovery
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PRPAIN201305UV02 }
     * 
     */
    public PRPAIN201305UV02 createPRPAIN201305UV02() {
        return new PRPAIN201305UV02();
    }

    /**
     * Create an instance of {@link PRPAIN201305UV02MCCIMT000100UV01Message }
     * 
     */
    public PRPAIN201305UV02MCCIMT000100UV01Message createPRPAIN201305UV02MCCIMT000100UV01Message() {
        return new PRPAIN201305UV02MCCIMT000100UV01Message();
    }

    /**
     * Create an instance of {@link CS }
     * 
     */
    public CS createCS() {
        return new CS();
    }

    /**
     * Create an instance of {@link II }
     * 
     */
    public II createII() {
        return new II();
    }

    /**
     * Create an instance of {@link TS }
     * 
     */
    public TS createTS() {
        return new TS();
    }

    /**
     * Create an instance of {@link ST }
     * 
     */
    public ST createST() {
        return new ST();
    }

    /**
     * Create an instance of {@link INT }
     * 
     */
    public INT createINT() {
        return new INT();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01Receiver }
     * 
     */
    public MCCIMT000100UV01Receiver createMCCIMT000100UV01Receiver() {
        return new MCCIMT000100UV01Receiver();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01RespondTo }
     * 
     */
    public MCCIMT000100UV01RespondTo createMCCIMT000100UV01RespondTo() {
        return new MCCIMT000100UV01RespondTo();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01Sender }
     * 
     */
    public MCCIMT000100UV01Sender createMCCIMT000100UV01Sender() {
        return new MCCIMT000100UV01Sender();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01AttentionLine }
     * 
     */
    public MCCIMT000100UV01AttentionLine createMCCIMT000100UV01AttentionLine() {
        return new MCCIMT000100UV01AttentionLine();
    }

    /**
     * Create an instance of {@link PRPAIN201305UV02QUQIMT021001UV01ControlActProcess }
     * 
     */
    public PRPAIN201305UV02QUQIMT021001UV01ControlActProcess createPRPAIN201305UV02QUQIMT021001UV01ControlActProcess() {
        return new PRPAIN201305UV02QUQIMT021001UV01ControlActProcess();
    }

    /**
     * Create an instance of {@link ANYNonNull }
     * 
     */
    public ANYNonNull createANYNonNull() {
        return new ANYNonNull();
    }

    /**
     * Create an instance of {@link RTOMOPQ }
     * 
     */
    public RTOMOPQ createRTOMOPQ() {
        return new RTOMOPQ();
    }

    /**
     * Create an instance of {@link IVLPPDPQ }
     * 
     */
    public IVLPPDPQ createIVLPPDPQ() {
        return new IVLPPDPQ();
    }

    /**
     * Create an instance of {@link AdxpPostalCode }
     * 
     */
    public AdxpPostalCode createAdxpPostalCode() {
        return new AdxpPostalCode();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectDeceasedTime }
     * 
     */
    public PRPAMT201306UV02LivingSubjectDeceasedTime createPRPAMT201306UV02LivingSubjectDeceasedTime() {
        return new PRPAMT201306UV02LivingSubjectDeceasedTime();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectBirthTime }
     * 
     */
    public PRPAMT201306UV02LivingSubjectBirthTime createPRPAMT201306UV02LivingSubjectBirthTime() {
        return new PRPAMT201306UV02LivingSubjectBirthTime();
    }

    /**
     * Create an instance of {@link AdxpDeliveryInstallationArea }
     * 
     */
    public AdxpDeliveryInstallationArea createAdxpDeliveryInstallationArea() {
        return new AdxpDeliveryInstallationArea();
    }

    /**
     * Create an instance of {@link IVLPPDTS }
     * 
     */
    public IVLPPDTS createIVLPPDTS() {
        return new IVLPPDTS();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02MothersMaidenName }
     * 
     */
    public PRPAMT201306UV02MothersMaidenName createPRPAMT201306UV02MothersMaidenName() {
        return new PRPAMT201306UV02MothersMaidenName();
    }

    /**
     * Create an instance of {@link BXITCD }
     * 
     */
    public BXITCD createBXITCD() {
        return new BXITCD();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01LocatedEntity }
     * 
     */
    public MCCIMT000100UV01LocatedEntity createMCCIMT000100UV01LocatedEntity() {
        return new MCCIMT000100UV01LocatedEntity();
    }

    /**
     * Create an instance of {@link RTOPQPQ }
     * 
     */
    public RTOPQPQ createRTOPQPQ() {
        return new RTOPQPQ();
    }

    /**
     * Create an instance of {@link COCTMT040203UV01NotificationParty }
     * 
     */
    public COCTMT040203UV01NotificationParty createCOCTMT040203UV01NotificationParty() {
        return new COCTMT040203UV01NotificationParty();
    }

    /**
     * Create an instance of {@link IVXBPPDTS }
     * 
     */
    public IVXBPPDTS createIVXBPPDTS() {
        return new IVXBPPDTS();
    }

    /**
     * Create an instance of {@link COCTMT150000UV02OrganizationPartOf }
     * 
     */
    public COCTMT150000UV02OrganizationPartOf createCOCTMT150000UV02OrganizationPartOf() {
        return new COCTMT150000UV02OrganizationPartOf();
    }

    /**
     * Create an instance of {@link AdxpBuildingNumberSuffix }
     * 
     */
    public AdxpBuildingNumberSuffix createAdxpBuildingNumberSuffix() {
        return new AdxpBuildingNumberSuffix();
    }

    /**
     * Create an instance of {@link SXCMCD }
     * 
     */
    public SXCMCD createSXCMCD() {
        return new SXCMCD();
    }

    /**
     * Create an instance of {@link IVXBPPDPQ }
     * 
     */
    public IVXBPPDPQ createIVXBPPDPQ() {
        return new IVXBPPDPQ();
    }

    /**
     * Create an instance of {@link REAL }
     * 
     */
    public REAL createREAL() {
        return new REAL();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01Requires }
     * 
     */
    public MCAIMT900001UV01Requires createMCAIMT900001UV01Requires() {
        return new MCAIMT900001UV01Requires();
    }

    /**
     * Create an instance of {@link COCTMT150000UV02Person }
     * 
     */
    public COCTMT150000UV02Person createCOCTMT150000UV02Person() {
        return new COCTMT150000UV02Person();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01EntityRsp }
     * 
     */
    public MCCIMT000100UV01EntityRsp createMCCIMT000100UV01EntityRsp() {
        return new MCCIMT000100UV01EntityRsp();
    }

    /**
     * Create an instance of {@link SXCMPQ }
     * 
     */
    public SXCMPQ createSXCMPQ() {
        return new SXCMPQ();
    }

    /**
     * Create an instance of {@link AdxpStreetAddressLine }
     * 
     */
    public AdxpStreetAddressLine createAdxpStreetAddressLine() {
        return new AdxpStreetAddressLine();
    }

    /**
     * Create an instance of {@link AdxpDeliveryInstallationType }
     * 
     */
    public AdxpDeliveryInstallationType createAdxpDeliveryInstallationType() {
        return new AdxpDeliveryInstallationType();
    }

    /**
     * Create an instance of {@link COCTMT030203UV02Person }
     * 
     */
    public COCTMT030203UV02Person createCOCTMT030203UV02Person() {
        return new COCTMT030203UV02Person();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectId }
     * 
     */
    public PRPAMT201306UV02LivingSubjectId createPRPAMT201306UV02LivingSubjectId() {
        return new PRPAMT201306UV02LivingSubjectId();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01Role }
     * 
     */
    public MCAIMT900001UV01Role createMCAIMT900001UV01Role() {
        return new MCAIMT900001UV01Role();
    }

    /**
     * Create an instance of {@link AdxpDeliveryAddressLine }
     * 
     */
    public AdxpDeliveryAddressLine createAdxpDeliveryAddressLine() {
        return new AdxpDeliveryAddressLine();
    }

    /**
     * Create an instance of {@link EnFamily }
     * 
     */
    public EnFamily createEnFamily() {
        return new EnFamily();
    }

    /**
     * Create an instance of {@link SXCMMO }
     * 
     */
    public SXCMMO createSXCMMO() {
        return new SXCMMO();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectName }
     * 
     */
    public PRPAMT201306UV02LivingSubjectName createPRPAMT201306UV02LivingSubjectName() {
        return new PRPAMT201306UV02LivingSubjectName();
    }

    /**
     * Create an instance of {@link AdxpPrecinct }
     * 
     */
    public AdxpPrecinct createAdxpPrecinct() {
        return new AdxpPrecinct();
    }

    /**
     * Create an instance of {@link PIVLTS }
     * 
     */
    public PIVLTS createPIVLTS() {
        return new PIVLTS();
    }

    /**
     * Create an instance of {@link IVXBPQ }
     * 
     */
    public IVXBPQ createIVXBPQ() {
        return new IVXBPQ();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01RoleOther }
     * 
     */
    public COCTMT090100UV01RoleOther createCOCTMT090100UV01RoleOther() {
        return new COCTMT090100UV01RoleOther();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01DetectedIssueManagement }
     * 
     */
    public MCAIMT900001UV01DetectedIssueManagement createMCAIMT900001UV01DetectedIssueManagement() {
        return new MCAIMT900001UV01DetectedIssueManagement();
    }

    /**
     * Create an instance of {@link AdxpStreetNameBase }
     * 
     */
    public AdxpStreetNameBase createAdxpStreetNameBase() {
        return new AdxpStreetNameBase();
    }

    /**
     * Create an instance of {@link IVXBMO }
     * 
     */
    public IVXBMO createIVXBMO() {
        return new IVXBMO();
    }

    /**
     * Create an instance of {@link SXCMTS }
     * 
     */
    public SXCMTS createSXCMTS() {
        return new SXCMTS();
    }

    /**
     * Create an instance of {@link EIVLEvent }
     * 
     */
    public EIVLEvent createEIVLEvent() {
        return new EIVLEvent();
    }

    /**
     * Create an instance of {@link IVXBTS }
     * 
     */
    public IVXBTS createIVXBTS() {
        return new IVXBTS();
    }

    /**
     * Create an instance of {@link EnPrefix }
     * 
     */
    public EnPrefix createEnPrefix() {
        return new EnPrefix();
    }

    /**
     * Create an instance of {@link AdxpDeliveryInstallationQualifier }
     * 
     */
    public AdxpDeliveryInstallationQualifier createAdxpDeliveryInstallationQualifier() {
        return new AdxpDeliveryInstallationQualifier();
    }

    /**
     * Create an instance of {@link TEL }
     * 
     */
    public TEL createTEL() {
        return new TEL();
    }

    /**
     * Create an instance of {@link QUQIMT021001UV01InformationRecipient }
     * 
     */
    public QUQIMT021001UV01InformationRecipient createQUQIMT021001UV01InformationRecipient() {
        return new QUQIMT021001UV01InformationRecipient();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01SourceOf }
     * 
     */
    public MCAIMT900001UV01SourceOf createMCAIMT900001UV01SourceOf() {
        return new MCAIMT900001UV01SourceOf();
    }

    /**
     * Create an instance of {@link COCTMT710000UV01LocatedEntityHasParts }
     * 
     */
    public COCTMT710000UV01LocatedEntityHasParts createCOCTMT710000UV01LocatedEntityHasParts() {
        return new COCTMT710000UV01LocatedEntityHasParts();
    }

    /**
     * Create an instance of {@link IVLMO }
     * 
     */
    public IVLMO createIVLMO() {
        return new IVLMO();
    }

    /**
     * Create an instance of {@link IVLTS }
     * 
     */
    public IVLTS createIVLTS() {
        return new IVLTS();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01RoleOther }
     * 
     */
    public COCTMT090300UV01RoleOther createCOCTMT090300UV01RoleOther() {
        return new COCTMT090300UV01RoleOther();
    }

    /**
     * Create an instance of {@link IVLPQ }
     * 
     */
    public IVLPQ createIVLPQ() {
        return new IVLPQ();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02QueryByParameter }
     * 
     */
    public PRPAMT201306UV02QueryByParameter createPRPAMT201306UV02QueryByParameter() {
        return new PRPAMT201306UV02QueryByParameter();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01Agent }
     * 
     */
    public MCCIMT000100UV01Agent createMCCIMT000100UV01Agent() {
        return new MCCIMT000100UV01Agent();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02MinimumDegreeMatch }
     * 
     */
    public PRPAMT201306UV02MinimumDegreeMatch createPRPAMT201306UV02MinimumDegreeMatch() {
        return new PRPAMT201306UV02MinimumDegreeMatch();
    }

    /**
     * Create an instance of {@link EIVLPPDTS }
     * 
     */
    public EIVLPPDTS createEIVLPPDTS() {
        return new EIVLPPDTS();
    }

    /**
     * Create an instance of {@link AdxpUnitID }
     * 
     */
    public AdxpUnitID createAdxpUnitID() {
        return new AdxpUnitID();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02PatientAddress }
     * 
     */
    public PRPAMT201306UV02PatientAddress createPRPAMT201306UV02PatientAddress() {
        return new PRPAMT201306UV02PatientAddress();
    }

    /**
     * Create an instance of {@link SLISTTS }
     * 
     */
    public SLISTTS createSLISTTS() {
        return new SLISTTS();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01LicensedEntity }
     * 
     */
    public COCTMT090100UV01LicensedEntity createCOCTMT090100UV01LicensedEntity() {
        return new COCTMT090100UV01LicensedEntity();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02OtherIDsScopingOrganization }
     * 
     */
    public PRPAMT201306UV02OtherIDsScopingOrganization createPRPAMT201306UV02OtherIDsScopingOrganization() {
        return new PRPAMT201306UV02OtherIDsScopingOrganization();
    }

    /**
     * Create an instance of {@link SLISTPQ }
     * 
     */
    public SLISTPQ createSLISTPQ() {
        return new SLISTPQ();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02ParameterList }
     * 
     */
    public PRPAMT201306UV02ParameterList createPRPAMT201306UV02ParameterList() {
        return new PRPAMT201306UV02ParameterList();
    }

    /**
     * Create an instance of {@link ADXP }
     * 
     */
    public ADXP createADXP() {
        return new ADXP();
    }

    /**
     * Create an instance of {@link PQR }
     * 
     */
    public PQR createPQR() {
        return new PQR();
    }

    /**
     * Create an instance of {@link AdxpCareOf }
     * 
     */
    public AdxpCareOf createAdxpCareOf() {
        return new AdxpCareOf();
    }

    /**
     * Create an instance of {@link IVLREAL }
     * 
     */
    public IVLREAL createIVLREAL() {
        return new IVLREAL();
    }

    /**
     * Create an instance of {@link AdxpHouseNumber }
     * 
     */
    public AdxpHouseNumber createAdxpHouseNumber() {
        return new AdxpHouseNumber();
    }

    /**
     * Create an instance of {@link COCTMT070000UV01LocatedEntity }
     * 
     */
    public COCTMT070000UV01LocatedEntity createCOCTMT070000UV01LocatedEntity() {
        return new COCTMT070000UV01LocatedEntity();
    }

    /**
     * Create an instance of {@link AdxpCounty }
     * 
     */
    public AdxpCounty createAdxpCounty() {
        return new AdxpCounty();
    }

    /**
     * Create an instance of {@link SXCMREAL }
     * 
     */
    public SXCMREAL createSXCMREAL() {
        return new SXCMREAL();
    }

    /**
     * Create an instance of {@link EnGiven }
     * 
     */
    public EnGiven createEnGiven() {
        return new EnGiven();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01DetectedIssueEvent }
     * 
     */
    public MCAIMT900001UV01DetectedIssueEvent createMCAIMT900001UV01DetectedIssueEvent() {
        return new MCAIMT900001UV01DetectedIssueEvent();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01Member }
     * 
     */
    public COCTMT090300UV01Member createCOCTMT090300UV01Member() {
        return new COCTMT090300UV01Member();
    }

    /**
     * Create an instance of {@link BXITIVLPQ }
     * 
     */
    public BXITIVLPQ createBXITIVLPQ() {
        return new BXITIVLPQ();
    }

    /**
     * Create an instance of {@link COCTMT710000UV01LocatedEntityPartOf }
     * 
     */
    public COCTMT710000UV01LocatedEntityPartOf createCOCTMT710000UV01LocatedEntityPartOf() {
        return new COCTMT710000UV01LocatedEntityPartOf();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02MatchCriterionList }
     * 
     */
    public PRPAMT201306UV02MatchCriterionList createPRPAMT201306UV02MatchCriterionList() {
        return new PRPAMT201306UV02MatchCriterionList();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01LicensedEntity }
     * 
     */
    public COCTMT090300UV01LicensedEntity createCOCTMT090300UV01LicensedEntity() {
        return new COCTMT090300UV01LicensedEntity();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01Device }
     * 
     */
    public MCCIMT000100UV01Device createMCCIMT000100UV01Device() {
        return new MCCIMT000100UV01Device();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01Person }
     * 
     */
    public COCTMT090100UV01Person createCOCTMT090100UV01Person() {
        return new COCTMT090100UV01Person();
    }

    /**
     * Create an instance of {@link AdxpDelimiter }
     * 
     */
    public AdxpDelimiter createAdxpDelimiter() {
        return new AdxpDelimiter();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02PrincipalCareProvisionId }
     * 
     */
    public PRPAMT201306UV02PrincipalCareProvisionId createPRPAMT201306UV02PrincipalCareProvisionId() {
        return new PRPAMT201306UV02PrincipalCareProvisionId();
    }

    /**
     * Create an instance of {@link SXCMPPDPQ }
     * 
     */
    public SXCMPPDPQ createSXCMPPDPQ() {
        return new SXCMPPDPQ();
    }

    /**
     * Create an instance of {@link AD }
     * 
     */
    public AD createAD() {
        return new AD();
    }

    /**
     * Create an instance of {@link BL }
     * 
     */
    public BL createBL() {
        return new BL();
    }

    /**
     * Create an instance of {@link BN }
     * 
     */
    public BN createBN() {
        return new BN();
    }

    /**
     * Create an instance of {@link CD }
     * 
     */
    public CD createCD() {
        return new CD();
    }

    /**
     * Create an instance of {@link CE }
     * 
     */
    public CE createCE() {
        return new CE();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02PatientStatusCode }
     * 
     */
    public PRPAMT201306UV02PatientStatusCode createPRPAMT201306UV02PatientStatusCode() {
        return new PRPAMT201306UV02PatientStatusCode();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01Group }
     * 
     */
    public COCTMT090100UV01Group createCOCTMT090100UV01Group() {
        return new COCTMT090100UV01Group();
    }

    /**
     * Create an instance of {@link CO }
     * 
     */
    public CO createCO() {
        return new CO();
    }

    /**
     * Create an instance of {@link CR }
     * 
     */
    public CR createCR() {
        return new CR();
    }

    /**
     * Create an instance of {@link CV }
     * 
     */
    public CV createCV() {
        return new CV();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01Group }
     * 
     */
    public COCTMT090300UV01Group createCOCTMT090300UV01Group() {
        return new COCTMT090300UV01Group();
    }

    /**
     * Create an instance of {@link EN }
     * 
     */
    public EN createEN() {
        return new EN();
    }

    /**
     * Create an instance of {@link AdxpDirection }
     * 
     */
    public AdxpDirection createAdxpDirection() {
        return new AdxpDirection();
    }

    /**
     * Create an instance of {@link AdxpDeliveryMode }
     * 
     */
    public AdxpDeliveryMode createAdxpDeliveryMode() {
        return new AdxpDeliveryMode();
    }

    /**
     * Create an instance of {@link RTOQTYQTY }
     * 
     */
    public RTOQTYQTY createRTOQTYQTY() {
        return new RTOQTYQTY();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02PatientTelecom }
     * 
     */
    public PRPAMT201306UV02PatientTelecom createPRPAMT201306UV02PatientTelecom() {
        return new PRPAMT201306UV02PatientTelecom();
    }

    /**
     * Create an instance of {@link SXCMPPDTS }
     * 
     */
    public SXCMPPDTS createSXCMPPDTS() {
        return new SXCMPPDTS();
    }

    /**
     * Create an instance of {@link HXITPQ }
     * 
     */
    public HXITPQ createHXITPQ() {
        return new HXITPQ();
    }

    /**
     * Create an instance of {@link MO }
     * 
     */
    public MO createMO() {
        return new MO();
    }

    /**
     * Create an instance of {@link ON }
     * 
     */
    public ON createON() {
        return new ON();
    }

    /**
     * Create an instance of {@link PN }
     * 
     */
    public PN createPN() {
        return new PN();
    }

    /**
     * Create an instance of {@link PQ }
     * 
     */
    public PQ createPQ() {
        return new PQ();
    }

    /**
     * Create an instance of {@link AdxpUnitType }
     * 
     */
    public AdxpUnitType createAdxpUnitType() {
        return new AdxpUnitType();
    }

    /**
     * Create an instance of {@link COCTMT150000UV02Organization }
     * 
     */
    public COCTMT150000UV02Organization createCOCTMT150000UV02Organization() {
        return new COCTMT150000UV02Organization();
    }

    /**
     * Create an instance of {@link SC }
     * 
     */
    public SC createSC() {
        return new SC();
    }

    /**
     * Create an instance of {@link TN }
     * 
     */
    public TN createTN() {
        return new TN();
    }

    /**
     * Create an instance of {@link COCTMT150003UV03Organization }
     * 
     */
    public COCTMT150003UV03Organization createCOCTMT150003UV03Organization() {
        return new COCTMT150003UV03Organization();
    }

    /**
     * Create an instance of {@link QUQIMT021001UV01DataEnterer }
     * 
     */
    public QUQIMT021001UV01DataEnterer createQUQIMT021001UV01DataEnterer() {
        return new QUQIMT021001UV01DataEnterer();
    }

    /**
     * Create an instance of {@link AdxpCity }
     * 
     */
    public AdxpCity createAdxpCity() {
        return new AdxpCity();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02MatchWeight }
     * 
     */
    public PRPAMT201306UV02MatchWeight createPRPAMT201306UV02MatchWeight() {
        return new PRPAMT201306UV02MatchWeight();
    }

    /**
     * Create an instance of {@link COCTMT030203UV02LanguageCommunication }
     * 
     */
    public COCTMT030203UV02LanguageCommunication createCOCTMT030203UV02LanguageCommunication() {
        return new COCTMT030203UV02LanguageCommunication();
    }

    /**
     * Create an instance of {@link AdxpState }
     * 
     */
    public AdxpState createAdxpState() {
        return new AdxpState();
    }

    /**
     * Create an instance of {@link IVXBINT }
     * 
     */
    public IVXBINT createIVXBINT() {
        return new IVXBINT();
    }

    /**
     * Create an instance of {@link SXCMINT }
     * 
     */
    public SXCMINT createSXCMINT() {
        return new SXCMINT();
    }

    /**
     * Create an instance of {@link UVPTS }
     * 
     */
    public UVPTS createUVPTS() {
        return new UVPTS();
    }

    /**
     * Create an instance of {@link AdxpStreetNameType }
     * 
     */
    public AdxpStreetNameType createAdxpStreetNameType() {
        return new AdxpStreetNameType();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01LanguageCommunication }
     * 
     */
    public COCTMT090100UV01LanguageCommunication createCOCTMT090100UV01LanguageCommunication() {
        return new COCTMT090100UV01LanguageCommunication();
    }

    /**
     * Create an instance of {@link AdxpPostBox }
     * 
     */
    public AdxpPostBox createAdxpPostBox() {
        return new AdxpPostBox();
    }

    /**
     * Create an instance of {@link AdxpDeliveryModeIdentifier }
     * 
     */
    public AdxpDeliveryModeIdentifier createAdxpDeliveryModeIdentifier() {
        return new AdxpDeliveryModeIdentifier();
    }

    /**
     * Create an instance of {@link SXPRTS }
     * 
     */
    public SXPRTS createSXPRTS() {
        return new SXPRTS();
    }

    /**
     * Create an instance of {@link AdxpAdditionalLocator }
     * 
     */
    public AdxpAdditionalLocator createAdxpAdditionalLocator() {
        return new AdxpAdditionalLocator();
    }

    /**
     * Create an instance of {@link QUQIMT021001UV01AuthorOrPerformer }
     * 
     */
    public QUQIMT021001UV01AuthorOrPerformer createQUQIMT021001UV01AuthorOrPerformer() {
        return new QUQIMT021001UV01AuthorOrPerformer();
    }

    /**
     * Create an instance of {@link HXITCE }
     * 
     */
    public HXITCE createHXITCE() {
        return new HXITCE();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectBirthPlaceName }
     * 
     */
    public PRPAMT201306UV02LivingSubjectBirthPlaceName createPRPAMT201306UV02LivingSubjectBirthPlaceName() {
        return new PRPAMT201306UV02LivingSubjectBirthPlaceName();
    }

    /**
     * Create an instance of {@link AdxpStreetName }
     * 
     */
    public AdxpStreetName createAdxpStreetName() {
        return new AdxpStreetName();
    }

    /**
     * Create an instance of {@link QUQIMT021001UV01Overseer }
     * 
     */
    public QUQIMT021001UV01Overseer createQUQIMT021001UV01Overseer() {
        return new QUQIMT021001UV01Overseer();
    }

    /**
     * Create an instance of {@link IVLINT }
     * 
     */
    public IVLINT createIVLINT() {
        return new IVLINT();
    }

    /**
     * Create an instance of {@link AdxpCountry }
     * 
     */
    public AdxpCountry createAdxpCountry() {
        return new AdxpCountry();
    }

    /**
     * Create an instance of {@link PPDPQ }
     * 
     */
    public PPDPQ createPPDPQ() {
        return new PPDPQ();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02SortControl }
     * 
     */
    public PRPAMT201306UV02SortControl createPRPAMT201306UV02SortControl() {
        return new PRPAMT201306UV02SortControl();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02PrincipalCareProviderId }
     * 
     */
    public PRPAMT201306UV02PrincipalCareProviderId createPRPAMT201306UV02PrincipalCareProviderId() {
        return new PRPAMT201306UV02PrincipalCareProviderId();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01AssignedPerson }
     * 
     */
    public COCTMT090100UV01AssignedPerson createCOCTMT090100UV01AssignedPerson() {
        return new COCTMT090100UV01AssignedPerson();
    }

    /**
     * Create an instance of {@link ENXP }
     * 
     */
    public ENXP createENXP() {
        return new ENXP();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01Device }
     * 
     */
    public COCTMT090300UV01Device createCOCTMT090300UV01Device() {
        return new COCTMT090300UV01Device();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01Organization }
     * 
     */
    public MCCIMT000100UV01Organization createMCCIMT000100UV01Organization() {
        return new MCCIMT000100UV01Organization();
    }

    /**
     * Create an instance of {@link QUQIMT021001UV01Reason }
     * 
     */
    public QUQIMT021001UV01Reason createQUQIMT021001UV01Reason() {
        return new QUQIMT021001UV01Reason();
    }

    /**
     * Create an instance of {@link EnSuffix }
     * 
     */
    public EnSuffix createEnSuffix() {
        return new EnSuffix();
    }

    /**
     * Create an instance of {@link COCTMT150003UV03Person }
     * 
     */
    public COCTMT150003UV03Person createCOCTMT150003UV03Person() {
        return new COCTMT150003UV03Person();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01Subject }
     * 
     */
    public MCAIMT900001UV01Subject createMCAIMT900001UV01Subject() {
        return new MCAIMT900001UV01Subject();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01AssignedDevice }
     * 
     */
    public COCTMT090300UV01AssignedDevice createCOCTMT090300UV01AssignedDevice() {
        return new COCTMT090300UV01AssignedDevice();
    }

    /**
     * Create an instance of {@link EIVLTS }
     * 
     */
    public EIVLTS createEIVLTS() {
        return new EIVLTS();
    }

    /**
     * Create an instance of {@link COCTMT090100UV01Member }
     * 
     */
    public COCTMT090100UV01Member createCOCTMT090100UV01Member() {
        return new COCTMT090100UV01Member();
    }

    /**
     * Create an instance of {@link GLISTPQ }
     * 
     */
    public GLISTPQ createGLISTPQ() {
        return new GLISTPQ();
    }

    /**
     * Create an instance of {@link MCCIMT000100UV01Place }
     * 
     */
    public MCCIMT000100UV01Place createMCCIMT000100UV01Place() {
        return new MCCIMT000100UV01Place();
    }

    /**
     * Create an instance of {@link IVXBREAL }
     * 
     */
    public IVXBREAL createIVXBREAL() {
        return new IVXBREAL();
    }

    /**
     * Create an instance of {@link RTO }
     * 
     */
    public RTO createRTO() {
        return new RTO();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectAdministrativeGender }
     * 
     */
    public PRPAMT201306UV02LivingSubjectAdministrativeGender createPRPAMT201306UV02LivingSubjectAdministrativeGender() {
        return new PRPAMT201306UV02LivingSubjectAdministrativeGender();
    }

    /**
     * Create an instance of {@link GLISTTS }
     * 
     */
    public GLISTTS createGLISTTS() {
        return new GLISTTS();
    }

    /**
     * Create an instance of {@link PIVLPPDTS }
     * 
     */
    public PIVLPPDTS createPIVLPPDTS() {
        return new PIVLPPDTS();
    }

    /**
     * Create an instance of {@link EnDelimiter }
     * 
     */
    public EnDelimiter createEnDelimiter() {
        return new EnDelimiter();
    }

    /**
     * Create an instance of {@link COCTMT150000UV02OrganizationContains }
     * 
     */
    public COCTMT150000UV02OrganizationContains createCOCTMT150000UV02OrganizationContains() {
        return new COCTMT150000UV02OrganizationContains();
    }

    /**
     * Create an instance of {@link AdxpCensusTract }
     * 
     */
    public AdxpCensusTract createAdxpCensusTract() {
        return new AdxpCensusTract();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02MatchAlgorithm }
     * 
     */
    public PRPAMT201306UV02MatchAlgorithm createPRPAMT201306UV02MatchAlgorithm() {
        return new PRPAMT201306UV02MatchAlgorithm();
    }

    /**
     * Create an instance of {@link PRPAMT201306UV02LivingSubjectBirthPlaceAddress }
     * 
     */
    public PRPAMT201306UV02LivingSubjectBirthPlaceAddress createPRPAMT201306UV02LivingSubjectBirthPlaceAddress() {
        return new PRPAMT201306UV02LivingSubjectBirthPlaceAddress();
    }

    /**
     * Create an instance of {@link COCTMT150003UV03ContactParty }
     * 
     */
    public COCTMT150003UV03ContactParty createCOCTMT150003UV03ContactParty() {
        return new COCTMT150003UV03ContactParty();
    }

    /**
     * Create an instance of {@link AdxpHouseNumberNumeric }
     * 
     */
    public AdxpHouseNumberNumeric createAdxpHouseNumberNumeric() {
        return new AdxpHouseNumberNumeric();
    }

    /**
     * Create an instance of {@link PPDTS }
     * 
     */
    public PPDTS createPPDTS() {
        return new PPDTS();
    }

    /**
     * Create an instance of {@link COCTMT710000UV01Place }
     * 
     */
    public COCTMT710000UV01Place createCOCTMT710000UV01Place() {
        return new COCTMT710000UV01Place();
    }

    /**
     * Create an instance of {@link Thumbnail }
     * 
     */
    public Thumbnail createThumbnail() {
        return new Thumbnail();
    }

    /**
     * Create an instance of {@link COCTMT150000UV02ContactParty }
     * 
     */
    public COCTMT150000UV02ContactParty createCOCTMT150000UV02ContactParty() {
        return new COCTMT150000UV02ContactParty();
    }

    /**
     * Create an instance of {@link COCTMT090300UV01LanguageCommunication }
     * 
     */
    public COCTMT090300UV01LanguageCommunication createCOCTMT090300UV01LanguageCommunication() {
        return new COCTMT090300UV01LanguageCommunication();
    }

    /**
     * Create an instance of {@link MCAIMT900001UV01ActOrderRequired }
     * 
     */
    public MCAIMT900001UV01ActOrderRequired createMCAIMT900001UV01ActOrderRequired() {
        return new MCAIMT900001UV01ActOrderRequired();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLREAL.class)
    public JAXBElement<REAL> createIVLREALWidth(REAL value) {
        return new JAXBElement<REAL>(_IVLREALWidth_QNAME, REAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLREAL.class)
    public JAXBElement<REAL> createIVLREALCenter(REAL value) {
        return new JAXBElement<REAL>(_IVLREALCenter_QNAME, REAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLREAL.class)
    public JAXBElement<IVXBREAL> createIVLREALLow(IVXBREAL value) {
        return new JAXBElement<IVXBREAL>(_IVLREALLow_QNAME, IVXBREAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLREAL.class)
    public JAXBElement<IVXBREAL> createIVLREALHigh(IVXBREAL value) {
        return new JAXBElement<IVXBREAL>(_IVLREALHigh_QNAME, IVXBREAL.class, IVLREAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLTS.class)
    public JAXBElement<PQ> createIVLTSWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLREALWidth_QNAME, PQ.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLTS.class)
    public JAXBElement<TS> createIVLTSCenter(TS value) {
        return new JAXBElement<TS>(_IVLREALCenter_QNAME, TS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLTS.class)
    public JAXBElement<IVXBTS> createIVLTSLow(IVXBTS value) {
        return new JAXBElement<IVXBTS>(_IVLREALLow_QNAME, IVXBTS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLTS.class)
    public JAXBElement<IVXBTS> createIVLTSHigh(IVXBTS value) {
        return new JAXBElement<IVXBTS>(_IVLREALHigh_QNAME, IVXBTS.class, IVLTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "partOrganization", scope = COCTMT150000UV02OrganizationContains.class)
    public JAXBElement<COCTMT150000UV02Organization> createCOCTMT150000UV02OrganizationContainsPartOrganization(COCTMT150000UV02Organization value) {
        return new JAXBElement<COCTMT150000UV02Organization>(_COCTMT150000UV02OrganizationContainsPartOrganization_QNAME, COCTMT150000UV02Organization.class, COCTMT150000UV02OrganizationContains.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT070000UV01LocatedEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "asLocatedEntity", scope = COCTMT090300UV01Device.class)
    public JAXBElement<COCTMT070000UV01LocatedEntity> createCOCTMT090300UV01DeviceAsLocatedEntity(COCTMT070000UV01LocatedEntity value) {
        return new JAXBElement<COCTMT070000UV01LocatedEntity>(_COCTMT090300UV01DeviceAsLocatedEntity_QNAME, COCTMT070000UV01LocatedEntity.class, COCTMT090300UV01Device.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTWidth(INT value) {
        return new JAXBElement<INT>(_IVLREALWidth_QNAME, INT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLINT.class)
    public JAXBElement<INT> createIVLINTCenter(INT value) {
        return new JAXBElement<INT>(_IVLREALCenter_QNAME, INT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLINT.class)
    public JAXBElement<IVXBINT> createIVLINTLow(IVXBINT value) {
        return new JAXBElement<IVXBINT>(_IVLREALLow_QNAME, IVXBINT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLINT.class)
    public JAXBElement<IVXBINT> createIVLINTHigh(IVXBINT value) {
        return new JAXBElement<IVXBINT>(_IVLREALHigh_QNAME, IVXBINT.class, IVLINT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "contactPerson", scope = COCTMT150000UV02ContactParty.class)
    public JAXBElement<COCTMT150000UV02Person> createCOCTMT150000UV02ContactPartyContactPerson(COCTMT150000UV02Person value) {
        return new JAXBElement<COCTMT150000UV02Person>(_COCTMT150000UV02ContactPartyContactPerson_QNAME, COCTMT150000UV02Person.class, COCTMT150000UV02ContactParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT710000UV01Place }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "locatedPlace", scope = COCTMT710000UV01LocatedEntityHasParts.class)
    public JAXBElement<COCTMT710000UV01Place> createCOCTMT710000UV01LocatedEntityHasPartsLocatedPlace(COCTMT710000UV01Place value) {
        return new JAXBElement<COCTMT710000UV01Place>(_COCTMT710000UV01LocatedEntityHasPartsLocatedPlace_QNAME, COCTMT710000UV01Place.class, COCTMT710000UV01LocatedEntityHasParts.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150003UV03Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "issuingOrganization", scope = COCTMT090300UV01LicensedEntity.class)
    public JAXBElement<COCTMT150003UV03Organization> createCOCTMT090300UV01LicensedEntityIssuingOrganization(COCTMT150003UV03Organization value) {
        return new JAXBElement<COCTMT150003UV03Organization>(_COCTMT090300UV01LicensedEntityIssuingOrganization_QNAME, COCTMT150003UV03Organization.class, COCTMT090300UV01LicensedEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDTS.class)
    public JAXBElement<PPDPQ> createIVLPPDTSWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLREALWidth_QNAME, PPDPQ.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDTS.class)
    public JAXBElement<PPDTS> createIVLPPDTSCenter(PPDTS value) {
        return new JAXBElement<PPDTS>(_IVLREALCenter_QNAME, PPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDTS.class)
    public JAXBElement<IVXBPPDTS> createIVLPPDTSLow(IVXBPPDTS value) {
        return new JAXBElement<IVXBPPDTS>(_IVLREALLow_QNAME, IVXBPPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDTS.class)
    public JAXBElement<IVXBPPDTS> createIVLPPDTSHigh(IVXBPPDTS value) {
        return new JAXBElement<IVXBPPDTS>(_IVLREALHigh_QNAME, IVXBPPDTS.class, IVLPPDTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPPDPQ.class)
    public JAXBElement<PPDPQ> createIVLPPDPQWidth(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLREALWidth_QNAME, PPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPPDPQ.class)
    public JAXBElement<PPDPQ> createIVLPPDPQCenter(PPDPQ value) {
        return new JAXBElement<PPDPQ>(_IVLREALCenter_QNAME, PPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPPDPQ.class)
    public JAXBElement<IVXBPPDPQ> createIVLPPDPQLow(IVXBPPDPQ value) {
        return new JAXBElement<IVXBPPDPQ>(_IVLREALLow_QNAME, IVXBPPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPPDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPPDPQ.class)
    public JAXBElement<IVXBPPDPQ> createIVLPPDPQHigh(IVXBPPDPQ value) {
        return new JAXBElement<IVXBPPDPQ>(_IVLREALHigh_QNAME, IVXBPPDPQ.class, IVLPPDPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "representedOrganization", scope = COCTMT090100UV01AssignedPerson.class)
    public JAXBElement<COCTMT150000UV02Organization> createCOCTMT090100UV01AssignedPersonRepresentedOrganization(COCTMT150000UV02Organization value) {
        return new JAXBElement<COCTMT150000UV02Organization>(_COCTMT090100UV01AssignedPersonRepresentedOrganization_QNAME, COCTMT150000UV02Organization.class, COCTMT090100UV01AssignedPerson.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT090100UV01Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "assignedPerson", scope = COCTMT090100UV01AssignedPerson.class)
    public JAXBElement<COCTMT090100UV01Person> createCOCTMT090100UV01AssignedPersonAssignedPerson(COCTMT090100UV01Person value) {
        return new JAXBElement<COCTMT090100UV01Person>(_COCTMT090100UV01AssignedPersonAssignedPerson_QNAME, COCTMT090100UV01Person.class, COCTMT090100UV01AssignedPerson.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PRPAMT201306UV02MatchAlgorithm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "matchAlgorithm", scope = PRPAMT201306UV02MatchCriterionList.class)
    public JAXBElement<PRPAMT201306UV02MatchAlgorithm> createPRPAMT201306UV02MatchCriterionListMatchAlgorithm(PRPAMT201306UV02MatchAlgorithm value) {
        return new JAXBElement<PRPAMT201306UV02MatchAlgorithm>(_PRPAMT201306UV02MatchCriterionListMatchAlgorithm_QNAME, PRPAMT201306UV02MatchAlgorithm.class, PRPAMT201306UV02MatchCriterionList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PRPAMT201306UV02MatchWeight }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "matchWeight", scope = PRPAMT201306UV02MatchCriterionList.class)
    public JAXBElement<PRPAMT201306UV02MatchWeight> createPRPAMT201306UV02MatchCriterionListMatchWeight(PRPAMT201306UV02MatchWeight value) {
        return new JAXBElement<PRPAMT201306UV02MatchWeight>(_PRPAMT201306UV02MatchCriterionListMatchWeight_QNAME, PRPAMT201306UV02MatchWeight.class, PRPAMT201306UV02MatchCriterionList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PRPAMT201306UV02MinimumDegreeMatch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "minimumDegreeMatch", scope = PRPAMT201306UV02MatchCriterionList.class)
    public JAXBElement<PRPAMT201306UV02MinimumDegreeMatch> createPRPAMT201306UV02MatchCriterionListMinimumDegreeMatch(PRPAMT201306UV02MinimumDegreeMatch value) {
        return new JAXBElement<PRPAMT201306UV02MinimumDegreeMatch>(_PRPAMT201306UV02MatchCriterionListMinimumDegreeMatch_QNAME, PRPAMT201306UV02MinimumDegreeMatch.class, PRPAMT201306UV02MatchCriterionList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT070000UV01LocatedEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "asLocatedEntity", scope = COCTMT150000UV02Person.class)
    public JAXBElement<COCTMT070000UV01LocatedEntity> createCOCTMT150000UV02PersonAsLocatedEntity(COCTMT070000UV01LocatedEntity value) {
        return new JAXBElement<COCTMT070000UV01LocatedEntity>(_COCTMT090300UV01DeviceAsLocatedEntity_QNAME, COCTMT070000UV01LocatedEntity.class, COCTMT150000UV02Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT090300UV01Device }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "assignedDevice", scope = COCTMT090300UV01AssignedDevice.class)
    public JAXBElement<COCTMT090300UV01Device> createCOCTMT090300UV01AssignedDeviceAssignedDevice(COCTMT090300UV01Device value) {
        return new JAXBElement<COCTMT090300UV01Device>(_COCTMT090300UV01AssignedDeviceAssignedDevice_QNAME, COCTMT090300UV01Device.class, COCTMT090300UV01AssignedDevice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "representedOrganization", scope = COCTMT090300UV01AssignedDevice.class)
    public JAXBElement<COCTMT150000UV02Organization> createCOCTMT090300UV01AssignedDeviceRepresentedOrganization(COCTMT150000UV02Organization value) {
        return new JAXBElement<COCTMT150000UV02Organization>(_COCTMT090100UV01AssignedPersonRepresentedOrganization_QNAME, COCTMT150000UV02Organization.class, COCTMT090300UV01AssignedDevice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT040203UV01NotificationParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "notificationParty", scope = MCCIMT000100UV01Organization.class)
    public JAXBElement<COCTMT040203UV01NotificationParty> createMCCIMT000100UV01OrganizationNotificationParty(COCTMT040203UV01NotificationParty value) {
        return new JAXBElement<COCTMT040203UV01NotificationParty>(_MCCIMT000100UV01OrganizationNotificationParty_QNAME, COCTMT040203UV01NotificationParty.class, MCCIMT000100UV01Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOWidth(MO value) {
        return new JAXBElement<MO>(_IVLREALWidth_QNAME, MO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLMO.class)
    public JAXBElement<MO> createIVLMOCenter(MO value) {
        return new JAXBElement<MO>(_IVLREALCenter_QNAME, MO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLMO.class)
    public JAXBElement<IVXBMO> createIVLMOLow(IVXBMO value) {
        return new JAXBElement<IVXBMO>(_IVLREALLow_QNAME, IVXBMO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLMO.class)
    public JAXBElement<IVXBMO> createIVLMOHigh(IVXBMO value) {
        return new JAXBElement<IVXBMO>(_IVLREALHigh_QNAME, IVXBMO.class, IVLMO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT710000UV01Place }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "location", scope = COCTMT710000UV01LocatedEntityPartOf.class)
    public JAXBElement<COCTMT710000UV01Place> createCOCTMT710000UV01LocatedEntityPartOfLocation(COCTMT710000UV01Place value) {
        return new JAXBElement<COCTMT710000UV01Place>(_COCTMT710000UV01LocatedEntityPartOfLocation_QNAME, COCTMT710000UV01Place.class, COCTMT710000UV01LocatedEntityPartOf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PRPAMT201306UV02QueryByParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "queryByParameter", scope = PRPAIN201305UV02QUQIMT021001UV01ControlActProcess.class)
    public JAXBElement<PRPAMT201306UV02QueryByParameter> createPRPAIN201305UV02QUQIMT021001UV01ControlActProcessQueryByParameter(PRPAMT201306UV02QueryByParameter value) {
        return new JAXBElement<PRPAMT201306UV02QueryByParameter>(_PRPAIN201305UV02QUQIMT021001UV01ControlActProcessQueryByParameter_QNAME, PRPAMT201306UV02QueryByParameter.class, PRPAIN201305UV02QUQIMT021001UV01ControlActProcess.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT030203UV02Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "contactPerson", scope = COCTMT040203UV01NotificationParty.class)
    public JAXBElement<COCTMT030203UV02Person> createCOCTMT040203UV01NotificationPartyContactPerson(COCTMT030203UV02Person value) {
        return new JAXBElement<COCTMT030203UV02Person>(_COCTMT150000UV02ContactPartyContactPerson_QNAME, COCTMT030203UV02Person.class, COCTMT040203UV01NotificationParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150003UV03Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "contactOrganization", scope = COCTMT040203UV01NotificationParty.class)
    public JAXBElement<COCTMT150003UV03Organization> createCOCTMT040203UV01NotificationPartyContactOrganization(COCTMT150003UV03Organization value) {
        return new JAXBElement<COCTMT150003UV03Organization>(_COCTMT040203UV01NotificationPartyContactOrganization_QNAME, COCTMT150003UV03Organization.class, COCTMT040203UV01NotificationParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnFamily }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "family", scope = EN.class)
    public JAXBElement<EnFamily> createENFamily(EnFamily value) {
        return new JAXBElement<EnFamily>(_ENFamily_QNAME, EnFamily.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnSuffix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "suffix", scope = EN.class)
    public JAXBElement<EnSuffix> createENSuffix(EnSuffix value) {
        return new JAXBElement<EnSuffix>(_ENSuffix_QNAME, EnSuffix.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "validTime", scope = EN.class)
    public JAXBElement<IVLTS> createENValidTime(IVLTS value) {
        return new JAXBElement<IVLTS>(_ENValidTime_QNAME, IVLTS.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnDelimiter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "delimiter", scope = EN.class)
    public JAXBElement<EnDelimiter> createENDelimiter(EnDelimiter value) {
        return new JAXBElement<EnDelimiter>(_ENDelimiter_QNAME, EnDelimiter.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnPrefix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "prefix", scope = EN.class)
    public JAXBElement<EnPrefix> createENPrefix(EnPrefix value) {
        return new JAXBElement<EnPrefix>(_ENPrefix_QNAME, EnPrefix.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnGiven }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "given", scope = EN.class)
    public JAXBElement<EnGiven> createENGiven(EnGiven value) {
        return new JAXBElement<EnGiven>(_ENGiven_QNAME, EnGiven.class, EN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "wholeOrganization", scope = COCTMT150000UV02OrganizationPartOf.class)
    public JAXBElement<COCTMT150000UV02Organization> createCOCTMT150000UV02OrganizationPartOfWholeOrganization(COCTMT150000UV02Organization value) {
        return new JAXBElement<COCTMT150000UV02Organization>(_COCTMT150000UV02OrganizationPartOfWholeOrganization_QNAME, COCTMT150000UV02Organization.class, COCTMT150000UV02OrganizationPartOf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PRPAMT201306UV02MatchCriterionList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "matchCriterionList", scope = PRPAMT201306UV02QueryByParameter.class)
    public JAXBElement<PRPAMT201306UV02MatchCriterionList> createPRPAMT201306UV02QueryByParameterMatchCriterionList(PRPAMT201306UV02MatchCriterionList value) {
        return new JAXBElement<PRPAMT201306UV02MatchCriterionList>(_PRPAMT201306UV02QueryByParameterMatchCriterionList_QNAME, PRPAMT201306UV02MatchCriterionList.class, PRPAMT201306UV02QueryByParameter.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MCCIMT000100UV01Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "representedOrganization", scope = MCCIMT000100UV01Agent.class)
    public JAXBElement<MCCIMT000100UV01Organization> createMCCIMT000100UV01AgentRepresentedOrganization(MCCIMT000100UV01Organization value) {
        return new JAXBElement<MCCIMT000100UV01Organization>(_COCTMT090100UV01AssignedPersonRepresentedOrganization_QNAME, MCCIMT000100UV01Organization.class, MCCIMT000100UV01Agent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "scopingOrganization", scope = COCTMT090100UV01RoleOther.class)
    public JAXBElement<COCTMT150000UV02Organization> createCOCTMT090100UV01RoleOtherScopingOrganization(COCTMT150000UV02Organization value) {
        return new JAXBElement<COCTMT150000UV02Organization>(_COCTMT090100UV01RoleOtherScopingOrganization_QNAME, COCTMT150000UV02Organization.class, COCTMT090100UV01RoleOther.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MCCIMT000100UV01Place }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "location", scope = MCCIMT000100UV01LocatedEntity.class)
    public JAXBElement<MCCIMT000100UV01Place> createMCCIMT000100UV01LocatedEntityLocation(MCCIMT000100UV01Place value) {
        return new JAXBElement<MCCIMT000100UV01Place>(_COCTMT710000UV01LocatedEntityPartOfLocation_QNAME, MCCIMT000100UV01Place.class, MCCIMT000100UV01LocatedEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MCCIMT000100UV01Agent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "asAgent", scope = MCCIMT000100UV01Device.class)
    public JAXBElement<MCCIMT000100UV01Agent> createMCCIMT000100UV01DeviceAsAgent(MCCIMT000100UV01Agent value) {
        return new JAXBElement<MCCIMT000100UV01Agent>(_MCCIMT000100UV01DeviceAsAgent_QNAME, MCCIMT000100UV01Agent.class, MCCIMT000100UV01Device.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150000UV02Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "scopingOrganization", scope = COCTMT090300UV01RoleOther.class)
    public JAXBElement<COCTMT150000UV02Organization> createCOCTMT090300UV01RoleOtherScopingOrganization(COCTMT150000UV02Organization value) {
        return new JAXBElement<COCTMT150000UV02Organization>(_COCTMT090100UV01RoleOtherScopingOrganization_QNAME, COCTMT150000UV02Organization.class, COCTMT090300UV01RoleOther.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150003UV03Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "issuingOrganization", scope = COCTMT090100UV01LicensedEntity.class)
    public JAXBElement<COCTMT150003UV03Organization> createCOCTMT090100UV01LicensedEntityIssuingOrganization(COCTMT150003UV03Organization value) {
        return new JAXBElement<COCTMT150003UV03Organization>(_COCTMT090300UV01LicensedEntityIssuingOrganization_QNAME, COCTMT150003UV03Organization.class, COCTMT090100UV01LicensedEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDirection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "direction", scope = AD.class)
    public JAXBElement<AdxpDirection> createADDirection(AdxpDirection value) {
        return new JAXBElement<AdxpDirection>(_ADDirection_QNAME, AdxpDirection.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetAddressLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetAddressLine", scope = AD.class)
    public JAXBElement<AdxpStreetAddressLine> createADStreetAddressLine(AdxpStreetAddressLine value) {
        return new JAXBElement<AdxpStreetAddressLine>(_ADStreetAddressLine_QNAME, AdxpStreetAddressLine.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "state", scope = AD.class)
    public JAXBElement<AdxpState> createADState(AdxpState value) {
        return new JAXBElement<AdxpState>(_ADState_QNAME, AdxpState.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDelimiter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "delimiter", scope = AD.class)
    public JAXBElement<AdxpDelimiter> createADDelimiter(AdxpDelimiter value) {
        return new JAXBElement<AdxpDelimiter>(_ENDelimiter_QNAME, AdxpDelimiter.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryMode", scope = AD.class)
    public JAXBElement<AdxpDeliveryMode> createADDeliveryMode(AdxpDeliveryMode value) {
        return new JAXBElement<AdxpDeliveryMode>(_ADDeliveryMode_QNAME, AdxpDeliveryMode.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetName", scope = AD.class)
    public JAXBElement<AdxpStreetName> createADStreetName(AdxpStreetName value) {
        return new JAXBElement<AdxpStreetName>(_ADStreetName_QNAME, AdxpStreetName.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpUnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "unitType", scope = AD.class)
    public JAXBElement<AdxpUnitType> createADUnitType(AdxpUnitType value) {
        return new JAXBElement<AdxpUnitType>(_ADUnitType_QNAME, AdxpUnitType.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SXCMTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "useablePeriod", scope = AD.class)
    public JAXBElement<SXCMTS> createADUseablePeriod(SXCMTS value) {
        return new JAXBElement<SXCMTS>(_ADUseablePeriod_QNAME, SXCMTS.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCensusTract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "censusTract", scope = AD.class)
    public JAXBElement<AdxpCensusTract> createADCensusTract(AdxpCensusTract value) {
        return new JAXBElement<AdxpCensusTract>(_ADCensusTract_QNAME, AdxpCensusTract.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCounty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "county", scope = AD.class)
    public JAXBElement<AdxpCounty> createADCounty(AdxpCounty value) {
        return new JAXBElement<AdxpCounty>(_ADCounty_QNAME, AdxpCounty.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpHouseNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "houseNumber", scope = AD.class)
    public JAXBElement<AdxpHouseNumber> createADHouseNumber(AdxpHouseNumber value) {
        return new JAXBElement<AdxpHouseNumber>(_ADHouseNumber_QNAME, AdxpHouseNumber.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpPostalCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postalCode", scope = AD.class)
    public JAXBElement<AdxpPostalCode> createADPostalCode(AdxpPostalCode value) {
        return new JAXBElement<AdxpPostalCode>(_ADPostalCode_QNAME, AdxpPostalCode.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpHouseNumberNumeric }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "houseNumberNumeric", scope = AD.class)
    public JAXBElement<AdxpHouseNumberNumeric> createADHouseNumberNumeric(AdxpHouseNumberNumeric value) {
        return new JAXBElement<AdxpHouseNumberNumeric>(_ADHouseNumberNumeric_QNAME, AdxpHouseNumberNumeric.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetNameBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetNameBase", scope = AD.class)
    public JAXBElement<AdxpStreetNameBase> createADStreetNameBase(AdxpStreetNameBase value) {
        return new JAXBElement<AdxpStreetNameBase>(_ADStreetNameBase_QNAME, AdxpStreetNameBase.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "city", scope = AD.class)
    public JAXBElement<AdxpCity> createADCity(AdxpCity value) {
        return new JAXBElement<AdxpCity>(_ADCity_QNAME, AdxpCity.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpBuildingNumberSuffix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "buildingNumberSuffix", scope = AD.class)
    public JAXBElement<AdxpBuildingNumberSuffix> createADBuildingNumberSuffix(AdxpBuildingNumberSuffix value) {
        return new JAXBElement<AdxpBuildingNumberSuffix>(_ADBuildingNumberSuffix_QNAME, AdxpBuildingNumberSuffix.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCountry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "country", scope = AD.class)
    public JAXBElement<AdxpCountry> createADCountry(AdxpCountry value) {
        return new JAXBElement<AdxpCountry>(_ADCountry_QNAME, AdxpCountry.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryInstallationQualifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryInstallationQualifier", scope = AD.class)
    public JAXBElement<AdxpDeliveryInstallationQualifier> createADDeliveryInstallationQualifier(AdxpDeliveryInstallationQualifier value) {
        return new JAXBElement<AdxpDeliveryInstallationQualifier>(_ADDeliveryInstallationQualifier_QNAME, AdxpDeliveryInstallationQualifier.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryInstallationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryInstallationType", scope = AD.class)
    public JAXBElement<AdxpDeliveryInstallationType> createADDeliveryInstallationType(AdxpDeliveryInstallationType value) {
        return new JAXBElement<AdxpDeliveryInstallationType>(_ADDeliveryInstallationType_QNAME, AdxpDeliveryInstallationType.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpUnitID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "unitID", scope = AD.class)
    public JAXBElement<AdxpUnitID> createADUnitID(AdxpUnitID value) {
        return new JAXBElement<AdxpUnitID>(_ADUnitID_QNAME, AdxpUnitID.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpCareOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "careOf", scope = AD.class)
    public JAXBElement<AdxpCareOf> createADCareOf(AdxpCareOf value) {
        return new JAXBElement<AdxpCareOf>(_ADCareOf_QNAME, AdxpCareOf.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryInstallationArea }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryInstallationArea", scope = AD.class)
    public JAXBElement<AdxpDeliveryInstallationArea> createADDeliveryInstallationArea(AdxpDeliveryInstallationArea value) {
        return new JAXBElement<AdxpDeliveryInstallationArea>(_ADDeliveryInstallationArea_QNAME, AdxpDeliveryInstallationArea.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpPrecinct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "precinct", scope = AD.class)
    public JAXBElement<AdxpPrecinct> createADPrecinct(AdxpPrecinct value) {
        return new JAXBElement<AdxpPrecinct>(_ADPrecinct_QNAME, AdxpPrecinct.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryAddressLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryAddressLine", scope = AD.class)
    public JAXBElement<AdxpDeliveryAddressLine> createADDeliveryAddressLine(AdxpDeliveryAddressLine value) {
        return new JAXBElement<AdxpDeliveryAddressLine>(_ADDeliveryAddressLine_QNAME, AdxpDeliveryAddressLine.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpStreetNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "streetNameType", scope = AD.class)
    public JAXBElement<AdxpStreetNameType> createADStreetNameType(AdxpStreetNameType value) {
        return new JAXBElement<AdxpStreetNameType>(_ADStreetNameType_QNAME, AdxpStreetNameType.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpDeliveryModeIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "deliveryModeIdentifier", scope = AD.class)
    public JAXBElement<AdxpDeliveryModeIdentifier> createADDeliveryModeIdentifier(AdxpDeliveryModeIdentifier value) {
        return new JAXBElement<AdxpDeliveryModeIdentifier>(_ADDeliveryModeIdentifier_QNAME, AdxpDeliveryModeIdentifier.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpAdditionalLocator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "additionalLocator", scope = AD.class)
    public JAXBElement<AdxpAdditionalLocator> createADAdditionalLocator(AdxpAdditionalLocator value) {
        return new JAXBElement<AdxpAdditionalLocator>(_ADAdditionalLocator_QNAME, AdxpAdditionalLocator.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdxpPostBox }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "postBox", scope = AD.class)
    public JAXBElement<AdxpPostBox> createADPostBox(AdxpPostBox value) {
        return new JAXBElement<AdxpPostBox>(_ADPostBox_QNAME, AdxpPostBox.class, AD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT070000UV01LocatedEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "asLocatedEntity", scope = COCTMT090100UV01Person.class)
    public JAXBElement<COCTMT070000UV01LocatedEntity> createCOCTMT090100UV01PersonAsLocatedEntity(COCTMT070000UV01LocatedEntity value) {
        return new JAXBElement<COCTMT070000UV01LocatedEntity>(_COCTMT090300UV01DeviceAsLocatedEntity_QNAME, COCTMT070000UV01LocatedEntity.class, COCTMT090100UV01Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT150003UV03Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "contactPerson", scope = COCTMT150003UV03ContactParty.class)
    public JAXBElement<COCTMT150003UV03Person> createCOCTMT150003UV03ContactPartyContactPerson(COCTMT150003UV03Person value) {
        return new JAXBElement<COCTMT150003UV03Person>(_COCTMT150000UV02ContactPartyContactPerson_QNAME, COCTMT150003UV03Person.class, COCTMT150003UV03ContactParty.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "width", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQWidth(PQ value) {
        return new JAXBElement<PQ>(_IVLREALWidth_QNAME, PQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "center", scope = IVLPQ.class)
    public JAXBElement<PQ> createIVLPQCenter(PQ value) {
        return new JAXBElement<PQ>(_IVLREALCenter_QNAME, PQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = IVLPQ.class)
    public JAXBElement<IVXBPQ> createIVLPQLow(IVXBPQ value) {
        return new JAXBElement<IVXBPQ>(_IVLREALLow_QNAME, IVXBPQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVXBPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = IVLPQ.class)
    public JAXBElement<IVXBPQ> createIVLPQHigh(IVXBPQ value) {
        return new JAXBElement<IVXBPQ>(_IVLREALHigh_QNAME, IVXBPQ.class, IVLPQ.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT090300UV01AssignedDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "assignedDevice", scope = QUQIMT021001UV01AuthorOrPerformer.class)
    public JAXBElement<COCTMT090300UV01AssignedDevice> createQUQIMT021001UV01AuthorOrPerformerAssignedDevice(COCTMT090300UV01AssignedDevice value) {
        return new JAXBElement<COCTMT090300UV01AssignedDevice>(_COCTMT090300UV01AssignedDeviceAssignedDevice_QNAME, COCTMT090300UV01AssignedDevice.class, QUQIMT021001UV01AuthorOrPerformer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT090100UV01AssignedPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "assignedPerson", scope = QUQIMT021001UV01AuthorOrPerformer.class)
    public JAXBElement<COCTMT090100UV01AssignedPerson> createQUQIMT021001UV01AuthorOrPerformerAssignedPerson(COCTMT090100UV01AssignedPerson value) {
        return new JAXBElement<COCTMT090100UV01AssignedPerson>(_COCTMT090100UV01AssignedPersonAssignedPerson_QNAME, COCTMT090100UV01AssignedPerson.class, QUQIMT021001UV01AuthorOrPerformer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link COCTMT710000UV01Place }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "location", scope = COCTMT070000UV01LocatedEntity.class)
    public JAXBElement<COCTMT710000UV01Place> createCOCTMT070000UV01LocatedEntityLocation(COCTMT710000UV01Place value) {
        return new JAXBElement<COCTMT710000UV01Place>(_COCTMT710000UV01LocatedEntityPartOfLocation_QNAME, COCTMT710000UV01Place.class, COCTMT070000UV01LocatedEntity.class, value);
    }

}
